services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Use Dockerfile.ultra-slim for even smaller image (experimental)
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override environment variables for local testing
      - QDRANT_URL=${QDRANT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_WEBHOOK_VERIFY_TOKEN=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TESTING=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/debug/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: joi-network