[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "fastapi run src/agent/interfaces/whatsapp/webhook_endpoint.py --port $PORT --host 0.0.0.0"
healthcheckPath = "/debug/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 